M48
; DRILL file {KiCad (6.0.0)} date Wed Jun  1 22:52:46 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-06-01T22:52:46+01:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.0)
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.200
%
G90
G05
T1
X189.98Y-121.88
X189.98Y-149.88
X218.25Y-121.85
X218.25Y-149.85
T0
M30
